language: python
python:
    - "3.5"
before_script:
    - pip install pytest coverage python-coveralls flake8
install: "python setup.py install"
script: coverage run --source {{ cookiecutter.slug_name }} -m py.test 
after_success:
    - flake8 --exit-zero
    - coverage report
    - coveralls
