language: python
python:
    - "3.5"
before_script:
    - pip install coverage python-coveralls flake8
install: "python setup.py install"
script: coverage run --source {{ cookiecutter.slug_name }} tests.py && flake8 --exit-zero && coverage report
after_success:
    - coveralls
