language: python
python:
    - "3.5"
before_script:
    - pip install cookiecutter pytest
script: 
    - cookiecutter . --no-input 
    - cd MyProject 
    - pip install -r requirements.txt
    - pip install -r requirements_dev.txt
    - python setup.py install 
    - py.test 
    - docker build . -t proj 
    - docker run proj python /code/tests/test_myproject.py 
services:
    - docker
